import Head from "next/head";

import Layout from "../components/Layout";
import HomePage from "../components/HomePage";
import TasksList from "../components/HomePage/TasksList";

export default function Home() {
  return (
    <>
      <Head>
        <title>To Do Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Layout>
          <HomePage>
            <TasksList/>
          </HomePage>
        </Layout>
      </main>
    </>
  );
}
